### ISSUE TITLE
Jogwheel ignores animation-delay

### ISSUE THREAD

**Issue by nordisk** [marionebl/jogwheel#129]
Hi.

Can jogwheel sync two animations on one timeline? For example: Have one `@keyframe rotation { … }` applied to two elements, where the second element has a animation-delay set. This makes the elements behaving like a rotation for an inifinite `animation-iteration`.

Is this something we can augment by using one jogwheel player?

It seems to us that jogwheel is ignoring the animation-delay set on that element and is playing both animations in unison – not chaining them.

**Comment by marionebl** [comment]
Hey @nordisk,

currently `animation-delay` is not respected by jogwheel, compare [get-player](https://github.com/marionebl/jogwheel/blob/37314de5d53771b23e6b4f50ef79c069076cb878/source/library/get-player.js#L36) but this is definitely on the roadmap for the near future. Do you have a shareable example case for this, preferable a codepen? 

I'd think synchronization of all animations on elements found in a JogWheel instance is a given. I'll roll around the idea and document expected edge cases here.

**Comment by nordisk** [comment]
Hey @marionebl – awesome news. I was about to roll my own implementation to control CSSAnimationKeyframes just when a colleague pinged me to your library. I will setup a codepen that demonstrates this.

In its essence:

```css
@keyframes fadeRotation{
        0%, 53%, 100% {
            opacity: 0;
        }
        3%, 50% {
            opacity: 1;
        }
    }

    .slide:first-of-type {
        animation: fadeRotation 10s ease;
    }

    .slide:nth-of-type(2) {
        animation: fadeRotation 10s ease 5s; 
    }

```
/cc @J7mbo
