### ISSUE TITLE
Can not seek; duration is undefined

### ISSUE THREAD

**Issue by KingHenne** [marionebl/jogwheel#78]
In Chrome (version 46.0.2490.86) there is no `effect` defined on `this.player` in https://github.com/marionebl/jogwheel/blob/master/source/library/index.js#L129. Thus `seek()` results in an error.

`element.animate(keyframes, options)` was called with these options (manipulated to work around two bugs):

```js
{duration: 1000, iterations: 100, easing: "linear", fill: "both"}
```

This is my css:

```css
@keyframes spin {
	from {
		transform: rotate(0);
	}
	to {
		transform: rotate(-360deg);
	}
}

[data-animated] {
	animation: spin 1s linear 100;
	animation-fill-mode: both;
	animation-play-state: paused;
}
```
